apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
      - name: mongo-deployment
        image: mongo
        envFrom:
          - secretRef:
              name: mongo-secret
        ports:
        - containerPort: 27017
